project:
  type: website
  output-dir: docs

website:
  title: "Density Surface Models, Golfo San Matias. Delfines Oscuro y Común"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Variables Ambientales"
        href: VariablesAmbientales.qmd
      - text: "Delfines Comunes"
        href: DelfinesComunes.qmd
      - text: "Delfines Oscuros"
        href: DelfinesOscuros.qmd


format:
  html:
    theme: cosmo
    toc: true
