project:
  type: website
  output-dir: docs

website:
  title: "Density Surface Models in Golfo San Matías"
  favicon: assets/favicon.png
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Variables Ambientales
        href: VariablesAmbientales.qmd
      - text: Delfines Oscuros
        href: DelfinesOscuros.qmd
      - text: Delfines Comunes
        href: DelfinesComunes.qmd
    right:
      - icon: github
        href: https://github.com/adbpatagonia/GolfoSanMatias_DolphinAbundance
    page-footer:
      left: "Alejandro Buren"



format:
  html:
    theme: cosmo
    css: assets/custom.css
    toc: true
    toc-location: right
    toc-depth: 2
    toc-expand: true
    smooth-scroll: true
    number-sections: true
    code-fold: show
    code-summary: "Show code"
    fig-responsive: true

bibliography: references/distancesampling.bib
csl: https://www.zotero.org/styles/marine-ecology-progress-series
link-citations: true
