---
  title: "Variables ambientales"
---

```{r}
#| include: false


library(here)

# source data (cached across pages) ----
source(file.path(here::here(), "analysis", "0_ReadData_Plots.r"))
# load_or_build_readdata()
```

Las estaciones fueron definidas:

-   <u>Verano</u>: Enero, Febrero, Marzo     
-   <u>Otoño</u>: Abril, Mayo, Junio     
-   <u>Invierno</u>: Julio, Agosto, Septiembre
-   <u>Primavera</u>: Octubre, Noviembre, Diciembre



Mapa del área en contexto    

```{r}
#| echo: false
#| message: false
#| warning: false

map.area.m
```


# Constante

```{r} 
#| echo: false
#| message: false
#| warning: false

p.depth
```

```{r} 
#| echo: false
#| message: false
#| warning: false

p.slope
```



# Escala: mensual

```{r} 
#| echo: false
#| message: false
#| warning: false
#| fig-width: 11
#| fig-height: 10

p.grad
```

```{r} 
#| echo: false
#| message: false
#| warning: false
#| fig-width: 11
#| fig-height: 10
p.sst
```

```{r} 
#| echo: false
#| message: false
#| warning: false
#| fig-width: 11
#| fig-height: 10
p.clo
```

```{r} 
#| echo: false
#| message: false
#| warning: false
#| fig-width: 11
#| fig-height: 10
p.distup
```


```{r} 
#| echo: false
#| message: false
#| warning: false
#| fig-width: 11
#| fig-height: 10
p.velvert
```
