---
title: "Density Surface Models, Golfo San Matias. Delfines Oscuros y Comun"
author: "Alejandro Buren (CONICET-IAA)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
# bibliography: hgams.bib   ## bibliographic library. Place in same folder as .Rmd
theme: jekyll-theme-slate
output:
  html_document:
    collapsed: no
    fig_caption: yes
    highlight: tango
    number_sections: yes
    smooth_scroll: yes
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("kableExtra")


options(scipen = 999)
options(warn = -1)

source(paste0(here::here(), "/analysis/1_DuskyDolphin.R"))
```

Este es un proyecto liderado por la Dra Silvana Dans .\


Los analisis se encuentran en [**este repositorio**](https://github.com/adbpatagonia/GolfoSanMatias_DolphinAbundance).  


# Datos    

Las estaciones fueron definidas:    

  * <u>Verano</u>: Enero, Febrero, Marzo   
  * Otoño: Abril, Mayo, Junio   
  * Invierno: Julio, Agosto, Septiembre
  * Primavera: Octubre, Noviembre, Diciembre

# Mapas de censos
## Delfin oscuro   

```{r maplo, fig.width  = 9, fig.height = 9, echo=FALSE, message=FALSE, warning=FALSE}
p.lo 
```

## Delfin común    

```{r mapdd, fig.width  = 9, fig.height = 9, echo=FALSE, message=FALSE, warning=FALSE}
p.dd
```

# Variables ambientales   
## Valores Anuales 

```{r mapdepth, fig.width  = 9, fig.height = 9, echo=FALSE, message=FALSE, warning=FALSE}
p.depth
```

```{r mapslope, fig.width  = 9, fig.height = 9, echo=FALSE, message=FALSE, warning=FALSE}
p.slope
```

```{r mapgrad, fig.width  = 9, fig.height = 9, echo=FALSE, message=FALSE, warning=FALSE}
p.grad
```

## Valores estacionales   

```{r mapsst, fig.width  = 9, fig.height = 9, echo=FALSE, message=FALSE, warning=FALSE}
p.sst
```

```{r mapclo, fig.width  = 9, fig.height = 9, echo=FALSE, message=FALSE, warning=FALSE}
p.clo
```

```{r mapdistup, fig.width  = 9, fig.height = 9, echo=FALSE, message=FALSE, warning=FALSE}
p.distup
```
