# Restore the DD decision-record artefacts after the clean re-run.
# These 16 files CANNOT be regenerated by current code: the four studies that
# wrote them hardcode, or compare against, the pre-2026-09-16 soap configuration
# that 4_CommonDolphin_DSM_soap.R no longer fits. See the header of
# analysis/9_RegenerateStudies_DD.R.
#
# Run AFTER 1_CommonDolphin.R and 9_RegenerateStudies_DD.R have finished.
# Copies, never moves -- the quarantine stays intact until the diff check passes.

$ErrorActionPreference = 'Stop'
$repo = 'D:\Buren_files\IAA\IAA_analyses\GolfoSanMatias_DolphinAbundance'
$q    = 'D:\Buren_files\IAA\IAA_analyses\_quarantine_DD_output_20260917\DSM'
$dst  = Join-Path $repo 'output\CommonDolphin\DSM'

$files = @(
  # UTIL_DSM_CovariateK_DD.R
  'DD_covariate_k_comparison.csv',
  'DD_soap_spatial_basis_check.csv',
  'DD_covariate_k20_diagnostics.csv',
  'DD_covariate_k20_denseknots.csv',
  'DD_covariate_2x2_grid.csv',
  'DD_covariate_2x2_attribution.csv',
  # UTIL_DSM_SoapRevised_DD.R
  'DD_soap_revised_selection.csv',
  'DD_soap_revised_paired.csv',
  # UTIL_DSM_RootogramKnots_DD.R
  'DD_rootogram_knotgrid.csv',
  'DD_rootogram_knotgrid_block.csv',
  'DD_rootogram_knotgrid.png',
  # UTIL_DSM_SoapTuning_DD.R
  'DD_soap_boundary_variants.csv',
  'DD_soap_knot_sweep.csv',
  'DD_soap_tuned_selection.csv',
  'DD_soap_knot_correlogram.csv',
  # UTIL_DSM_CovariateK_DD_Figure.R  (also rebuildable from the CSVs above)
  'DD_two_defects.png'
)

$missing = @()
foreach ($f in $files) {
  $src = Join-Path $q $f
  if (Test-Path $src) {
    # Overwriting here would mean the re-run wrote a file that should not exist.
    if (Test-Path (Join-Path $dst $f)) { Write-Warning "already present, NOT overwriting: $f" }
    else { Copy-Item $src (Join-Path $dst $f); Write-Host "restored  $f" }
  } else { $missing += $f }
}
if ($missing.Count) { Write-Warning ("missing from quarantine: " + ($missing -join ', ')) }
Write-Host ("`nrestored {0} of {1}" -f ($files.Count - $missing.Count), $files.Count)
