# Restore the DD decision-record artefacts after the clean re-run.
# These 18 files CANNOT be regenerated by current code: the studies that wrote
# them hardcode, or compare against, the pre-2026-09-16 soap configuration that
# 4_CommonDolphin_DSM_soap.R no longer fits. See the header of
# analysis/9_RegenerateStudies_DD.R.
#
# 16 go back to output\CommonDolphin\DSM\ under their own names (step 9 of the
# runbook, 2026-09-19). The last 2 were promoted on 2026-09-29 and go to
# output\CommonDolphin\Abundance\decision_records\ instead, because live scripts
# still write files with the SAME names in Abundance\ -- restoring them there
# would put a record where the next run overwrites it. See the README in that
# folder.
#
# Run AFTER 1_CommonDolphin.R and 9_RegenerateStudies_DD.R have finished.
# Copies, never moves -- the quarantine stays intact until the diff check passes.

$ErrorActionPreference = 'Stop'
$repo = 'D:\Buren_files\IAA\IAA_analyses\GolfoSanMatias_DolphinAbundance'
$qrt  = 'D:\Buren_files\IAA\IAA_analyses\_quarantine_DD_output_20260917'

$sets = @(
  @{ q = Join-Path $qrt 'DSM'
     dst = Join-Path $repo 'output\CommonDolphin\DSM'
     files = @(
       # UTIL_DSM_CovariateK_DD.R
       'DD_covariate_k_comparison.csv',
       'DD_soap_spatial_basis_check.csv',
       'DD_covariate_k20_diagnostics.csv',
       'DD_covariate_k20_denseknots.csv',
       'DD_covariate_2x2_grid.csv',
       'DD_covariate_2x2_attribution.csv',
       # UTIL_DSM_SoapRevised_DD.R
       'DD_soap_revised_selection.csv',
       'DD_soap_revised_paired.csv',
       # UTIL_DSM_RootogramKnots_DD.R
       'DD_rootogram_knotgrid.csv',
       'DD_rootogram_knotgrid_block.csv',
       'DD_rootogram_knotgrid.png',
       # UTIL_DSM_SoapTuning_DD.R
       'DD_soap_boundary_variants.csv',
       'DD_soap_knot_sweep.csv',
       'DD_soap_tuned_selection.csv',
       'DD_soap_knot_correlogram.csv',
       # UTIL_DSM_CovariateK_DD_Figure.R  (also rebuildable from the CSVs above)
       'DD_two_defects.png'
     ) },
  @{ q = Join-Path $qrt 'Abundance'
     dst = Join-Path $repo 'output\CommonDolphin\Abundance\decision_records'
     files = @(
       # 5_CommonDolphin_Abundance.R, 2026-09-02: the ORIGINAL soap arm
       # (41 knots, 3000/2000, k = 10), which the pipeline no longer fits
       'DD_abundance_season_year_soap.csv',
       # UTIL_DSM_TunedArm_MapsAbundance_DD.R, 2026-09-16: tuned vs THAT arm.
       # The copy the script rewrites in Abundance\ now compares tuned vs tuned.
       'DD_abundance_tuned_vs_original.png'
     ) }
)

$missing = @(); $total = 0
foreach ($s in $sets) {
  New-Item -ItemType Directory -Force $s.dst | Out-Null
  foreach ($f in $s.files) {
    $total++
    $src = Join-Path $s.q $f
    if (Test-Path $src) {
      # Overwriting here would mean the re-run wrote a file that should not exist.
      if (Test-Path (Join-Path $s.dst $f)) { Write-Warning "already present, NOT overwriting: $f" }
      else { Copy-Item $src (Join-Path $s.dst $f); Write-Host "restored  $f" }
    } else { $missing += $f }
  }
}
if ($missing.Count) { Write-Warning ("missing from quarantine: " + ($missing -join ', ')) }
Write-Host ("`nrestored {0} of {1}" -f ($total - $missing.Count), $total)
